### ISSUE TITLE
[Info] Training

### ISSUE THREAD

**Issue by bbday** [Lonegwadiwaitor/FunCaptcha-Solver#1]
Look good but missing training, then will be very hard help you to improve project

**Comment by Lonegwadiwaitor** [comment]
I decided against including the training for a few reasons

1. There is plenty of data out there to train your own models, perhaps even better than the ones I made.
2. Mine were never made for purpose anyway, Object Detection should be used instead of ML.NET Image Classification for the best possible results.
3. I wouldn't actually want to contribute to the botting of platforms, this was a project that was used for security research and for finding captcha suppression vulnerabilities.
